### ISSUE TITLE
Some of your guidelines seem unreasonable

### ISSUE THREAD

**Issue by jessuppi** [withspectrum/code-of-conduct#11]
I love your software but I feel someone needs to say this:

While it's commendable to want to have a welcoming, safe, and professional community, some of the rules in Code of Conduct seem a little bit extreme, and even hypocritical, and sound like the aggression that's currently overtaken many college campuses. You folks have created an incredible open source project here, why destroy it with such political activism like this...

You are going to ban people who:

- call a biological man "sir" by accident because they didn't know they're transgender, etc.
- say "hugs!" or other cutesy internet terms
- unwanted one-on-one chat (but you prevent [disabling DM features](https://github.com/withspectrum/spectrum/issues/5203))

> This code of conduct applies to Spectrum-sponsored spaces, but if you are being harassed by a member of the Spectrum community outside our spaces, we still want to know about it. We will take all good-faith reports of harassment by Spectrum community members seriously. This includes harassment outside our spaces and harassment that took place at any point in time. The abuse team reserves the right to exclude people from the Spectrum community based on their past behavior, including behavior outside Spectrum spaces and behavior towards people who are not in the Spectrum community.

So you prohibit using Spectrum for stalking and harassment, but you encourage your members to stalk and follow each other outside of Spectrum and report on their lifestyle choices and activities that might be offensive to the Spectrum founders? This just sounds kind of scary...

> In order to protect volunteers from abuse and burnout, we reserve the right to reject any report we believe to have been made in bad faith. The Spectrum team are not here to explain power differentials or other basic social justice concepts to you. Reports intended to silence legitimate criticism may be deleted without response.

You create extremely arbitrary and demanding behavior guidelines, but then "reserve the right" to ignore users who report being victimized or abused? Certain criticism and harassment of members is "legitimate" and shouldn't waste your time with being reported?

> We will respect confidentiality requests for the purpose of protecting victims of abuse. At our discretion, we may publicly name a person about whom we’ve received harassment complaints, or privately warn third parties about them, if we believe that doing so will increase the safety of Spectrum members or the general public. We will not name harassment victims without their affirmative consent.

And you also threaten to publicly name or criticize your members that you might disagree with in regard to their behavior on or off the Spectrum platform? I'm not even sure what this means, but it certainly doesn't sound very "welcoming"...

Anyway I know your platform is rather new, and your team is probably very tired with various bug reports and complaints and are trying to establish rules to make things easier to manage but with all respect, I encourage you to come up with more "mainstream" Terms Of Use.

Thanks so much for your time and efforts. Cheers!

**Comment by superbryntendo** [comment]
1. We "reserve the right" to take those actions. We investigate each issue thoroughly and speak to both parties wherever possible before taking action.
2. You can block individual users and prevent them from DMing you.
3. These terms are necessarily broad in terms of defining measures that may be taken - just like most mainstream ToS. They are different, in particular, in terms of making it clear that people who are often undersupported by mainstream ToS should be more safe here.
4. We do have separate Terms of Service, but we plan to continue to maintain a code of conduct that aligns with our personal values.
